---
name: "LazyTarget's Home Assistant Apps Repository Updater"
description: Tool for updating Home Assistant Apps repositories.
author: lazytarget

branding:
  color: red
  icon: thumbs-up

inputs:
  token:
    description: GitHub token that is allowed to write/commit to the target repo
    required: true
  repository:
    description: The app repository to update (e.g., lazytarget/repository)
    required: false
  trigger-ref:
    description: The ref of the branch or commit_id that caused the deploy of the app (e.g., edge or fbd6282)
    required: false
  app:
    description: Slug of the app to update the repository for
    required: false
  addon:
    description: (Deprecated) Use 'app' instead. Slug of the app to update the repository for
    required: false
  force:
    description: Force repository update, even if no changes are detected
    default: "false"
    required: false

runs:
  using: "docker"
  image: "action/Dockerfile"
